version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    
  dtu-pay-service:
    image: dtu-pay
    container_name: dtu-pay
    ports:
     - "8080:8080"
    
  student-id-service:
    image: student-id 
    container_name: student-id 

 
